name: DeluxeAuctions
main: me.sedattr.deluxeauctions.DeluxeAuctions

author: SedatTR
version: 4.3
api-version: 1.13
folia-supported: true

description: The best, cheap, advanced, fully customizable auction plugin; like popular server!
website: https://discord.gg/nchk86TKMT
softdepend:
  - Vault
  - CoinsEngine
  - HeadDatabase
  - PlaceholderAPI
  - PlayerPoints
  - Lands
  - UltraEconomy
  - LiteBans
  - AdvancedBan
  - DeluxeAuctionsDisplay
  - Skript
loadbefore:
  - DeluxeAuctionsDisplay
  - CMI

commands:
  auction:
    description: Default auction command.
    aliases: [deluxeauctions, ah, auc]
  auctionadmin:
    description: Default auction admin command.
    aliases: [deluxeauctionsadmin, ahadmin, aucadmin]
